name: McToQQ
version: '${project.version}'
main: net.bluemangoo.mctoqq.McToQQ
api-version: 1.17
authors: [ Bluemangoo , FengMing]
description: message between mc and qq
commands:
  mctoqq:
    description: "控制MCTOQQ"